[CodeGenManagerSettings]
# List of supported file extensions
supportedFileExtensions = [".h", ".hpp"]

# Files contained in the directories of this list will be parsed
toProcessDirectories = [
#	'''Path/To/Directory/To/Parse'''
]

# Files to parse which are not included in any directory of toParseDirectories
toProcessFiles = []

# Files contained in the directories of this list will be ignored
ignoredDirectories = [
#	'''Path/To/Output/Dir''',
#	'''Path/To/Directory/To/Ignore'''
]

# Files not to parse which are not included in any directory of ignoredDirectories
ignoredFiles = []


[CodeGenUnitSettings]
# Generated files will be located here
outputDirectory = '''Path/To/Output/Dir'''

# Uncomment if you generate code for an (dynamic) exported library
# Define the export macro so that the generator can export generated code as well when necessary
# exportSymbolMacroName = "EXAMPLE_IMPORT_EXPORT_MACRO"

[ParsingSettings]
# Used c++ version (supported values are: 17, 20)
cppVersion = 17

# Include directories of the project
projectIncludeDirectories = [
#	'''Path/To/Your/Project/Include'''
]

# Must be one of "msvc", "clang++", "g++"
compilerExeName = "clang++"

# Abort parsing on first encountered error
shouldAbortParsingOnFirstError = true

# Should parse all entities of a given type, whether they are annotated or not
shouldParseAllNamespaces = false
shouldParseAllClasses = false
shouldParseAllStructs = false
shouldParseAllVariables = false
shouldParseAllFields = false
shouldParseAllFunctions = false
shouldParseAllMethods = false
shouldParseAllEnums = false
shouldParseAllEnumValues = true

shouldLogDiagnostic = false

propertySeparator = ","
argumentSeparator = ","
argumentStartEncloser = "("
argumentEndEncloser = ")"

namespaceMacroName = "NAMESPACE"
classMacroName = "CLASS"
structMacroName = "STRUCT"
variableMacroName = "VARIABLE"
fieldMacroName = "FIELD"
functionMacroName = "FUNCTION"
methodMacroName = "METHOD"
enumMacroName = "ENUM"
enumValueMacroName = "ENUMVALUE"